#!/bin/bash

function exist () {
	if grep -q "$2" $1 ; then
		echo '0'
	else
		echo '1'
	fi
}

function replace_line () {
	cp $1 $1.old
	sed -i "/$2/c\\$3" $1 
	echo '0'
}

function add_line () {
	cp $1 $1.old
	echo "$2" >> $1
	echo '0'
}

function remove_line () {
	cp $1 $1.old
	if sed "\!${2}! d $3" $1 > $1.new ; then
		echo '0'
	else 
		echo '1'
	fi
	cp $1.new $1
	rm $1.new
}

function save_files () {
	mkdir -p /home/master1/ase20/original_files
	for f in `cat $1` ; do
		if test -e /home/master1/ase20/original_files/`basename $f` ; then
			echo /home/master1/ase20/original_files/`basename $f` exists
		else
			cp -a $f /home/master1/ase20/original_files/`basename $f`
		fi
	done
}

function reset_files () {
	for f in `cat $1` ; do
		cp -a /home/master1/ase20/original_files/`basename $f` $f
	done
}
